### ISSUE TITLE
ERROR on stop skill

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/skill-ovos-weather#23]
On a headless installation - raspbian bullseye, RPI3, install of ovos-core from pip, everytime I stop the skills I get this message from the skill

```
2023-02-21 00:42:58.836 - skills - ovos_workshop.skills.base:default_shutdown:1700 - ERROR - Failed to stop skill: skill-ovos-weather.openvoiceos
Traceback (most recent call last):
  File "/home/denix/ovos-core/lib/python3.9/site-packages/ovos_workshop/skills/base.py", line 1698, in default_shutdown
    self.stop()
  File "/home/denix/.local/share/mycroft/skills/skill-ovos-weather.openvoiceos/__init__.py", line 1139, in stop
    self.gui.release()
  File "/home/denix/ovos-core/lib/python3.9/site-packages/ovos_utils/gui.py", line 922, in release
    raise RuntimeError("bus not set, did you call self.bind() ?")
RuntimeError: bus not set, did you call self.bind() ?
```

**Comment by emphasize** [comment]
Still occuring?
