### ISSUE TITLE
When asking "quelle est la temperature" the skill fails

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-weather#59]
```
Mar 30 10:30:24 neon ovos-core[1547]: 2024-03-30 10:30:24.404 - skills - ovos_utils.file_utils:resolve_resource_file:163 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
Mar 30 10:30:24 neon ovos-core[1547]: 2024-03-30 10:30:24.421 - skill-ovos-weather.openvoiceos - ERROR - Expecting value: line 1 column 1 (char 0)
Mar 30 10:30:24 neon ovos-core[1547]: Traceback (most recent call last):
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/requests/models.py", line 971, in json
Mar 30 10:30:24 neon ovos-core[1547]:     return complexjson.loads(self.text, **kwargs)
Mar 30 10:30:24 neon ovos-core[1547]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
Mar 30 10:30:24 neon ovos-core[1547]:     return _default_decoder.decode(s)
Mar 30 10:30:24 neon ovos-core[1547]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
Mar 30 10:30:24 neon ovos-core[1547]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Mar 30 10:30:24 neon ovos-core[1547]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
Mar 30 10:30:24 neon ovos-core[1547]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Mar 30 10:30:24 neon ovos-core[1547]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mar 30 10:30:24 neon ovos-core[1547]: During handling of the above exception, another exception occurred:
Mar 30 10:30:24 neon ovos-core[1547]: Traceback (most recent call last):
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_utils/events.py", line 78, in wrapper
Mar 30 10:30:24 neon ovos-core[1547]:     handler(message)
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/__init__.py", line 215, in handle_current_temperature
Mar 30 10:30:24 neon ovos-core[1547]:     self._report_temperature(message, temperature_type="current")
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/__init__.py", line 854, in _report_temperature
Mar 30 10:30:24 neon ovos-core[1547]:     intent_data = self._get_intent_data(message)
Mar 30 10:30:24 neon ovos-core[1547]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/__init__.py", line 924, in _get_intent_data
Mar 30 10:30:24 neon ovos-core[1547]:     _dt = intent_data.intent_datetime
Mar 30 10:30:24 neon ovos-core[1547]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/weather_helpers/intent.py", line 110, in intent_datetime
Mar 30 10:30:24 neon ovos-core[1547]:     timezone=self.geolocation.get("timezone"),
Mar 30 10:30:24 neon ovos-core[1547]:              ^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/weather_helpers/intent.py", line 96, in geolocation
Mar 30 10:30:24 neon ovos-core[1547]:     self._geolocation = get_geolocation(self.location)
Mar 30 10:30:24 neon ovos-core[1547]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_weather/weather_helpers/util.py", line 100, in get_geolocation
Mar 30 10:30:24 neon ovos-core[1547]:     geolocation = geolocation_api.get_geolocation(location)
Mar 30 10:30:24 neon ovos-core[1547]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_backend_client/api.py", line 381, in get_geolocation
Mar 30 10:30:24 neon ovos-core[1547]:     return self.backend.geolocation_get(location)
Mar 30 10:30:24 neon ovos-core[1547]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_utils/__init__.py", line 95, in wrapped_f
Mar 30 10:30:24 neon ovos-core[1547]:     return f(*args, **kwargs)
Mar 30 10:30:24 neon ovos-core[1547]:            ^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_backend_client/backends/offline.py", line 202, in geolocation_get
Mar 30 10:30:24 neon ovos-core[1547]:     data = self.get(url, params={"q": location, "format": "json", "limit": 1}).json()[0]
Mar 30 10:30:24 neon ovos-core[1547]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 10:30:24 neon ovos-core[1547]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/requests/models.py", line 975, in json
Mar 30 10:30:24 neon ovos-core[1547]:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
Mar 30 10:30:24 neon ovos-core[1547]: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by goldyfruit** [comment]
Fixed.
